Repository yorkie-team/yorkie-ui-poc, pull requests merged in 2024-01, with the labels that each got.

#42 [Config] Setup storybook + config source
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .stylelintignore
  .stylelintrc.json
  README.md
  next.config.js
  package-lock.json
  package.json
  panda.config.ts
  postcss.config.cjs
  prettier.config.js
  src/app/page.tsx
  src/components/ui/button.ts
  src/components/ui/button/Button.mdx
  src/components/ui/button/Button.stories.tsx
  src/components/ui/button/Button.tsx
  src/components/ui/button/index.ts
  src/components/ui/index.ts
  src/components/ui/radio-button-group.ts
  src/components/ui/slider.ts
  src/components/ui/tabs.ts
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/header.css
  src/stories/page.css
  tsconfig.json
Labels: UI Component, Storybook

#47 [#33] Avatar storybook
  src/components/ui/avatar/Avatar.mdx
  src/components/ui/avatar/Avatar.stories.tsx
Labels: Storybook

#46 [#32] Avatar component
  panda.config.ts
  src/components/ui/avatar/Avatar.mdx
  src/components/ui/avatar/Avatar.stories.tsx
  src/components/ui/avatar/Avatar.tsx
  src/components/ui/avatar/AvatarSlotRecipe.tsx
  src/components/ui/avatar/index.ts
  src/components/ui/avatar/interface.ts
  src/components/ui/icons/index.ts
  src/components/ui/icons/user-icon.tsx
  src/components/ui/index.ts
  src/lib/utils/getInitials.ts
  tsconfig.json
Labels: UI Component

#55 [#5] Button Storybook
  src/components/ui/button/Button.mdx
  src/components/ui/button/Button.stories.tsx
Labels: Storybook

#56 [#14] Tooltip component
  panda.config.ts
  src/components/ui/tooltip/Tooltip.tsx
  src/components/ui/tooltip/TooltipRecipe.tsx
  src/components/ui/tooltip/index.ts
Labels: UI Component

#57 [#15] Tooltip Storybook
  package-lock.json
  package.json
  src/components/ui/index.ts
  src/components/ui/tooltip/Tooltip.mdx
  src/components/ui/tooltip/Tooltip.stories.tsx
  src/components/ui/tooltip/Tooltip.tsx
  src/components/ui/tooltip/index.ts
Labels: Storybook

#58 [#18] Select Component
  panda.config.ts
  src/components/ui/icons/down-icon.tsx
  src/components/ui/icons/index.ts
  src/components/ui/index.ts
  src/components/ui/select/Select.mdx
  src/components/ui/select/Select.stories.tsx
  src/components/ui/select/Select.tsx
  src/components/ui/select/SelectRecipe.tsx
  src/components/ui/select/index.ts
  styled-system/recipes/index.d.ts
  styled-system/recipes/index.mjs
Labels: UI Component
